# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 23:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedScripts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fiddle_name', models.CharField(default='myfiddle', max_length=100)),
                ('code', models.TextField(max_length=10000000)),
                ('commands', models.TextField(blank=True, default='', max_length=10000)),
                ('packages', models.TextField(blank=True, default='', max_length=10000)),
                ('private', models.BooleanField(default=False)),
                ('upload', models.FileField(blank=True, default='', upload_to='')),
                ('runs', models.BigIntegerField(blank=True, default=0)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScriptFiles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfiddleweb.Script')),
            ],
        ),
        migrations.CreateModel(
            name='StarredScripts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfiddleweb.Script')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='savedscripts',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyfiddleweb.Script'),
        ),
        migrations.AddField(
            model_name='savedscripts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
