# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyfiddleweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptRuns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='', max_length=200)),
                ('code', models.TextField(blank=True, max_length=10000000, null=True)),
            ],
        ),
    ]
