# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyfiddleweb', '0002_scriptruns'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='inputs',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='script',
            name='commands',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='script',
            name='packages',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
