# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyfiddleweb', '0003_auto_20170721_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='version',
            field=models.BooleanField(default=False),
        ),
    ]
