# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-30 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyfiddleweb', '0005_scriptcollaborators'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptruns',
            name='commands',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='scriptruns',
            name='inputs',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='scriptruns',
            name='packages',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='scriptruns',
            name='code',
            field=models.TextField(blank=True, default='', max_length=10000000, null=True),
        ),
    ]
