# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-09 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyfiddleweb', '0007_auto_20180128_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='envs',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
