# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-16 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyfiddleweb', '0008_script_envs'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptruns',
            name='envs',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
